# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 491))
        self.frame.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 70, 184, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.height = QtWidgets.QLineEdit(self.layoutWidget)
        self.height.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.weight = QtWidgets.QLineEdit(self.layoutWidget)
        self.weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.weight.setObjectName("weight")
        self.gridLayout.addWidget(self.weight, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 170, 239, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calculateB = QtWidgets.QPushButton(self.layoutWidget1)
        self.calculateB.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.calculateB.setObjectName("calculateB")
        self.gridLayout_2.addWidget(self.calculateB, 0, 0, 1, 1)
        self.resetB = QtWidgets.QPushButton(self.layoutWidget1)
        self.resetB.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.resetB.setObjectName("resetB")
        self.gridLayout_2.addWidget(self.resetB, 0, 1, 1, 1)
        self.exitB = QtWidgets.QPushButton(self.layoutWidget1)
        self.exitB.setStyleSheet("background-color: rgb(255, 85, 255);")
        self.exitB.setObjectName("exitB")
        self.gridLayout_2.addWidget(self.exitB, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BMI CALCULATOR"))
        self.label_2.setText(_translate("MainWindow", "Enter Height"))
        self.label_3.setText(_translate("MainWindow", "Enter Weight"))
        self.calculateB.setText(_translate("MainWindow", "Calculate"))
        self.resetB.setText(_translate("MainWindow", "Reset"))
        self.exitB.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
